services:
  photobook:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__SqlConnection=Server=photobook.db;Database=photobook_db;User Id=sa;Password=Taggia42!
      - ConnectionStrings__AzureStorageConnection=${STORAGEACCOUNTCONNECTION}
      - AppSettings__ContainerName=attachments
      - AppSettings__CognitiveServicesKey=${COGNITIVESERVICESKEY}
      - AppSettings__CognitiveServicesEndpoint=${COGNITIVESERVICESENDPOINT}
      - AppSettings__OtelEndpoint=${OTELENDPOINT}
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    ports:
      - "6999:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Taggia42!"
