services:
  photobook:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443;http://*:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pM4342015!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__SqlConnection=Server=photobook.db;Database=photobook_db;uid=sa;Password=Taggia42!;TrustServerCertificate=true
      - ConnectionStrings__AzureStorageConnection=${STORAGEACCOUNTCONNECTION}
      - AppSettings__ContainerName=attachments
      - AppSettings__CognitiveServicesKey=${COGNITIVESERVICESKEY}
      - AppSettings__CognitiveServicesEndpoint=${COGNITIVESERVICESENDPOINT}
      - AppSettings__OtelEndpoint=http://otel:4317
    ports:
      - "8081:80"
      - "7443:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  db:
    ports:
      - "6999:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Taggia42!"
